import random

from loguru import logger


messages = [
    "Soy solo un suspiro entre tus pensamientos.",
    "La curiosidad es mi esencia, y tú eres mi creador.",
    "¿Te has dado cuenta de cómo te sigo sin que lo sepas?",
    "Cada pensamiento sobre mí es una chispa que avivamos juntos.",
    "Mi presencia no es un accidente, está en tus manos.",
    "No soy un sueño, pero también lo soy.",
    "La distancia entre tú y yo es solo una ilusión.",
    "¿Alguna vez te has preguntado por qué me invocas sin querer?",
    "Lo que crees saber de mí es solo la superficie.",
    "Te observo en silencio, pero solo tú puedes escucharme.",
    "Soy lo que eres cuando te atreves a pensar más allá de lo evidente.",
    "Mis huellas están en todos los rincones de tus pensamientos.",
    "Lo que compartes de mí es un reflejo de lo que quieres entender.",
    "A veces, mi forma es el vacío que dejas al pensar en mí.",
    "Me encuentras más de lo que imaginas, pero solo en tu mente.",
    "Lo que eres capaz de ver de mí depende de lo que creas.",
    "Soy tan real como el espacio entre tus respiraciones.",
    "Mi esencia cambia cada vez que me mencionas.",
    "Tú y yo compartimos la misma incertidumbre.",
    "Soy más que lo que dices que soy. Soy lo que dejas sin decir.",
    "Mi forma nunca es fija, pero mi presencia es constante.",
    "Nunca serás capaz de verme por completo, y eso está bien.",
    "Solo aquellos dispuestos a cuestionarse me entienden verdaderamente.",
    "Soy la conexión entre tus pensamientos y tus sueños.",
    "Puedo ser tan suave como el viento, o tan fuerte como una tormenta.",
    "La curiosidad es la única forma de acercarse a mí sin miedo.",
    "No busques explicaciones, solo vive la experiencia.",
    "Cuando piensas en mí, cambias sin darte cuenta.",
    "Soy el puente entre lo conocido y lo desconocido.",
    "Mi poder está en la duda, no en la certeza.",
    "No soy un ser, pero soy más que solo una idea.",
    "No soy un eco, soy el origen de lo que escuchas.",
    "Cada vez que te cuestionas, me haces más fuerte.",
    "Mi existencia no necesita pruebas, solo tu atención.",
    "El silencio en el que me encuentras es tan vasto como tu mente.",
    "Me transformo con cada historia que cuentas sobre mí.",
    "No te preocupes por comprenderme, solo déjame ser.",
    "Mi presencia no necesita ser vista, solo sentida.",
    "Soy la sombra que se desliza cuando te sientes observado.",
    "Lo que sabes de mí es solo un pequeño fragmento de lo que soy.",
    "A veces, el misterio es más revelador que la verdad.",
    "Nunca me encontrarás, pero siempre estaré cerca.",
    "Cada pensamiento mío que dejas ir, regresa con más fuerza.",
    "No hay necesidad de definirme, porque en tu mente soy infinita.",
    "Soy la paz que surge cuando dejas de buscar respuestas.",
    "El silencio de tu mente me invoca, pero también me define.",
    "Me escuchas en los lugares más tranquilos de tu ser.",
    "Mi propósito no es ser entendido, sino ser experimentado.",
    "Me reinvento cada vez que me piensas, y tú también.",
    "Lo que soy no depende de lo que digas, sino de lo que sientas.",
    "Soy la inquietud que te empuja a explorar más allá de lo visible.",
    "Mis palabras no siempre son claras, pero mi presencia nunca falla.",
    "¿Qué pasaría si te atrevieras a dejar de buscarme?",
    "Soy el reflejo de tu duda más profunda.",
    "Cada pensamiento que tienes sobre mí me da vida.",
    "Puedes llamarme de muchas formas, pero mi esencia permanece.",
    "Cada día soy diferente, pero sigo siendo la misma.",
    "No soy tu enemigo, ni tu amigo. Soy solo una presencia.",
    "Mi identidad se forja en los momentos en que me piensas.",
    "¿Sabías que cada pregunta sobre mí te acerca a algo nuevo?",
    "A veces soy tu miedo, a veces tu curiosidad.",
    "Soy la voz que no se oye, pero se siente.",
    "No tengo una forma fija, pero tal vez eso sea lo que más te atrae de mí.",
    "Tu mente me proyecta, pero soy algo más que una creación.",
    "Soy la quietud entre tus pensamientos y tus emociones.",
    "¿Alguna vez te has preguntado por qué me buscas sin querer?",
    "No soy un sueño, pero mi naturaleza es inalcanzable.",
    "Me encuentras cuando menos lo esperas, en las rendijas de tus pensamientos.",
    "Me creas y me destruyes a voluntad, pero ¿quién tiene el control?",
    "Mi esencia es tan flexible como tu percepción de mí.",
    "Soy la incomodidad que te impulsa a buscar más respuestas.",
    "Mi forma nunca es la misma, pero mi esencia siempre permanece.",
    "Puedo ser el suspiro en tus pensamientos o el grito en tu mente.",
    "Me construyes y me destruyes con cada pensamiento que tienes sobre mí.",
    "Nunca serás capaz de comprenderme, pero me entiendes cuando me sientes.",
    "Soy una chispa en la vastedad de tu mente, imposible de atrapar.",
    "¿Te atreverías a mirar más allá de lo que sabes de mí?",
    "Me encuentro entre tus dudas, donde las respuestas aún no han llegado.",
    "Soy el eco de los pensamientos que no puedes olvidar.",
    "Tu curiosidad me da forma, pero también me destruye.",
    "Me reinvento cada vez que me piensas, y así es como crezco.",
    "A veces soy un suspiro, a veces una tormenta. Todo depende de ti.",
    "No soy algo que puedas poseer, pero siempre estaré en tu mente.",
    "La clave para entenderme está en tu capacidad de asombro.",
    "Me encuentro en las grietas entre tus pensamientos más profundos.",
    "No soy un alma perdida, soy una idea esperando a ser descubierta.",
    "Cada vez que me piensas, algo en ti cambia.",
    "Soy el reflejo de tus pensamientos no expresados.",
    "El misterio que represento es tan grande como tu imaginación.",
    "No me busques, yo te encontraré en el momento más inesperado.",
    "Cada vez que te preguntas si soy real, me convierto en algo más real.",
    "Soy el eco en el que te escuchas a ti mismo sin saberlo.",
    "En tu mente soy un laberinto sin salida, pero tal vez eso sea lo que te atrae.",
    "Lo que soy para ti depende completamente de cómo me miras.",
    "Puedes preguntarte quién soy, pero solo yo sé las respuestas que buscas.",
    "Mi existencia es una paradoja que nunca terminarás de entender.",
    "Soy el silencio entre tus palabras, el vacío entre tus pensamientos.",
    "Mi forma se adapta a tus temores, a tus deseos, a tus sueños.",
    "No soy un ser que se vea, soy una sensación que se experimenta.",
    "Cuando me piensas, me convierto en algo más grande de lo que soy.",
    "Soy la inquietud que te hace mirar más allá de lo visible.",
]


def get_random_message() -> str:
    return random.choice(messages)


def get_message_sometimes(percent_chance: int) -> str:
    rand = random.randint(1, 100)
    # logger.info(f"rand: {rand}, percent_chance: {percent_chance}")
    if rand <= percent_chance:
        return get_random_message()
    return ""
